using System.Collections.Generic;

namespace ThreeKingdom.Presentation.Screens
{
    /// <summary>
    /// 内部稳定 id → 玩家中文名的集中映射（占位期表现层用；后续可移入场景配置数据驱动）。
    /// 未登记的 id 回退原文，绝不崩 UI。<b>只影响展示，不影响权威 id</b>。
    /// </summary>
    public static class DisplayNames
    {
        private static readonly IReadOnlyDictionary<string, string> Names = new Dictionary<string, string>
        {
            ["subject-enemy-army"] = "敌军主力",
            ["advice-ambush"] = "设伏诱敌",
            ["faction-player"] = "本部",
            ["faction-lord"] = "君主",
            ["region-pass"] = "隘口",
            ["city-fanshui"] = "汜水关",
            ["city-hulao"] = "虎牢关",
            ["char-player-lord"] = "主公亲征",
            ["char-aide"] = "副将（军师）",

            // 群雄割据世界骨架（势力）。
            ["faction-yuan"] = "袁术",
            ["faction-sun"] = "孙吴",
            ["faction-cao"] = "曹操",
            ["faction-yuanshao"] = "袁绍",
            ["faction-liubei"] = "刘备",
            ["faction-lubu"] = "吕布",
            ["faction-liubiao"] = "刘表",
            ["faction-mateng"] = "马腾",
            ["faction-liuzhang"] = "刘璋",
            ["faction-zhanglu"] = "张鲁",
            ["faction-gongsun"] = "公孙瓒",
            // 城池。
            ["city-shouchun"] = "寿春",
            ["city-jianye"] = "建业",
            ["city-wujun"] = "吴郡",
            ["city-xuchang"] = "许昌",
            ["city-puyang"] = "濮阳",
            ["city-chenliu"] = "陈留",
            ["city-ye"] = "邺城",
            ["city-nanpi"] = "南皮",
            ["city-xiaopei"] = "小沛",
            ["city-xiapi"] = "下邳",
            ["city-xiangyang"] = "襄阳",
            ["city-xiliang"] = "西凉",
            ["city-chengdu"] = "成都",
            ["city-hanzhong"] = "汉中",
            ["city-beiping"] = "北平",
            // 君主。
            ["char-caocao"] = "曹操",
            ["char-yuanshao"] = "袁绍",
            ["char-liubei"] = "刘备",
            ["char-lubu"] = "吕布",
            ["char-liubiao"] = "刘表",
            ["char-mateng"] = "马腾",
            ["char-liuzhang"] = "刘璋",
            ["char-zhanglu"] = "张鲁",
            ["char-gongsun"] = "公孙瓒",
            ["char-sunquan"] = "孙权",
            ["char-yuan"] = "袁术",

            // 群雄割据扩充（势力）。
            ["faction-lijue"] = "李傕",
            ["faction-zhangxiu"] = "张绣",
            ["faction-kongrong"] = "孔融",
            ["faction-hansui"] = "韩遂",
            ["faction-shixie"] = "士燮",
            // 城池。
            ["city-juancheng"] = "鄄城",
            ["city-pingyuan"] = "平原",
            ["city-jinyang"] = "晋阳",
            ["city-runan"] = "汝南",
            ["city-kuaiji"] = "会稽",
            ["city-lujiang"] = "庐江",
            ["city-xuzhou"] = "徐州",
            ["city-jiangling"] = "江陵",
            ["city-jiangxia"] = "江夏",
            ["city-changsha"] = "长沙",
            ["city-jiangzhou"] = "江州",
            ["city-zitong"] = "梓潼",
            ["city-wuwei"] = "武威",
            ["city-jicheng"] = "蓟城",
            ["city-changan"] = "长安",
            ["city-luoyang"] = "洛阳",
            ["city-wancheng"] = "宛城",
            ["city-beihai"] = "北海",
            ["city-hanyang"] = "汉阳",
            ["city-jiaozhou"] = "交州",
            // 君主。
            ["char-sunce"] = "孙策",
            ["char-lijue"] = "李傕",
            ["char-zhangxiu"] = "张绣",
            ["char-kongrong"] = "孔融",
            ["char-hansui"] = "韩遂",
            ["char-shixie"] = "士燮",
            // 部将（武将目录 #2）。
            ["char-guanyu"] = "关羽",
            ["char-zhangfei"] = "张飞",
            ["char-zhaoyun"] = "赵云",
            ["char-zhugeliang"] = "诸葛亮",
            ["char-machao"] = "马超",
            ["char-huangzhong"] = "黄忠",
            ["char-weiyan"] = "魏延",
            ["char-pangtong"] = "庞统",
            ["char-jiangwei"] = "姜维",
            ["char-xiahoudun"] = "夏侯惇",
            ["char-zhangliao"] = "张辽",
            ["char-xuchu"] = "许褚",
            ["char-dianwei"] = "典韦",
            ["char-guojia"] = "郭嘉",
            ["char-xunyu"] = "荀彧",
            ["char-simayi"] = "司马懿",
            ["char-caoren"] = "曹仁",
            ["char-jiaxu"] = "贾诩",
            ["char-zhouyu"] = "周瑜",
            ["char-lusu"] = "鲁肃",
            ["char-lvmeng"] = "吕蒙",
            ["char-luxun"] = "陆逊",
            ["char-taishici"] = "太史慈",
            ["char-ganning"] = "甘宁",
            ["char-huanggai"] = "黄盖",
            ["char-yanliang"] = "颜良",
            ["char-wenchou"] = "文丑",
            ["char-gaoshun"] = "高顺",
            ["char-chengong"] = "陈宫",
            ["char-huaxiong"] = "华雄",
            ["char-haozhao"] = "郝昭",
            // 扩充批 1（演义名将）。
            ["char-xiahouyuan"] = "夏侯渊", ["char-zhanghe"] = "张郃", ["char-xuhuang"] = "徐晃",
            ["char-yujin"] = "于禁", ["char-yuejin"] = "乐进", ["char-lidian"] = "李典",
            ["char-caohong"] = "曹洪", ["char-caozhang"] = "曹彰", ["char-caopi"] = "曹丕",
            ["char-caozhi"] = "曹植", ["char-dengai"] = "邓艾", ["char-zhonghui"] = "钟会",
            ["char-guohuai"] = "郭淮", ["char-caozhen"] = "曹真", ["char-pangde"] = "庞德",
            ["char-wenpin"] = "文聘", ["char-chengyu"] = "程昱", ["char-simashi"] = "司马师",
            ["char-simazhao"] = "司马昭", ["char-huaxin"] = "华歆", ["char-manchong"] = "满宠",
            ["char-guanping"] = "关平", ["char-zhoucang"] = "周仓", ["char-liaohua"] = "廖化",
            ["char-madai"] = "马岱", ["char-wangping"] = "王平", ["char-guanxing"] = "关兴",
            ["char-zhangbao"] = "张苞", ["char-yanyan"] = "严颜", ["char-fazheng"] = "法正",
            ["char-masu"] = "马谡", ["char-jiangwan"] = "蒋琬", ["char-feiyi"] = "费祎",
            ["char-liyan"] = "李严", ["char-liufeng"] = "刘封",
            ["char-chengpu"] = "程普", ["char-handang"] = "韩当", ["char-zhoutai"] = "周泰",
            ["char-jiangqin"] = "蒋钦", ["char-chenwu"] = "陈武", ["char-lingtong"] = "凌统",
            ["char-xusheng"] = "徐盛", ["char-dingfeng"] = "丁奉", ["char-panzhang"] = "潘璋",
            ["char-zhuran"] = "朱然", ["char-zhugejin"] = "诸葛瑾", ["char-zhangzhao"] = "张昭",
            ["char-zhugeke"] = "诸葛恪", ["char-sunshangxiang"] = "孙尚香",
            ["char-dongzhuo"] = "董卓", ["char-liru"] = "李儒", ["char-zhangjiao"] = "张角",
            ["char-jiling"] = "纪灵", ["char-tianfeng"] = "田丰", ["char-jushou"] = "沮授",
            ["char-shenpei"] = "审配", ["char-gaolan"] = "高览", ["char-caimao"] = "蔡瑁",
            ["char-huangzu"] = "黄祖", ["char-zangba"] = "臧霸",
            // 扩充批 2。
            ["char-sunqian"] = "孙乾", ["char-mizhu"] = "糜竺", ["char-mifang"] = "糜芳",
            ["char-jianyong"] = "简雍", ["char-yiji"] = "伊籍", ["char-maliang"] = "马良",
            ["char-dengzhi"] = "邓芝", ["char-zhangyi"] = "张翼", ["char-zhangni"] = "张嶷",
            ["char-wuyi"] = "吴懿", ["char-huojun"] = "霍峻", ["char-mengda"] = "孟达",
            ["char-guansuo"] = "关索", ["char-zhugezhan"] = "诸葛瞻", ["char-fuqian"] = "傅佥",
            ["char-caoxiu"] = "曹休", ["char-caoshuang"] = "曹爽", ["char-wangshuang"] = "王双",
            ["char-tianyu"] = "田豫", ["char-qianzhao"] = "牵招", ["char-chentai"] = "陈泰",
            ["char-wangji"] = "王基", ["char-jiachong"] = "贾充", ["char-wangjun"] = "王濬",
            ["char-yanghu"] = "羊祜", ["char-duyu"] = "杜预", ["char-jiangji"] = "蒋济",
            ["char-liuye"] = "刘晔", ["char-chenqun"] = "陈群", ["char-zhongyao"] = "钟繇",
            ["char-caorui"] = "曹叡",
            ["char-sunjian"] = "孙坚", ["char-dongxi"] = "董袭", ["char-machongwu"] = "马忠",
            ["char-zhuhuan"] = "朱桓", ["char-quancong"] = "全琮", ["char-buzhi"] = "步骘",
            ["char-guyong"] = "顾雍", ["char-zhanghong"] = "张纮", ["char-kanze"] = "阚泽",
            ["char-lukang"] = "陆抗",
            ["char-huatuo"] = "华佗", ["char-zuoci"] = "左慈", ["char-yuji"] = "于吉",
            ["char-zhangbao-turban"] = "张宝", ["char-zhangliang-turban"] = "张梁", ["char-hejin"] = "何进",
            ["char-menghuo"] = "孟获", ["char-zhurong"] = "祝融", ["char-shamoke"] = "沙摩柯",
            ["char-zhangren"] = "张任", ["char-hanxuan"] = "韩玄", ["char-gongsunkang"] = "公孙康",
            ["char-tadun"] = "蹋顿", ["char-kebineng"] = "轲比能", ["char-yanbaihu"] = "严白虎",
            // 扩充批 3。
            ["char-xushu"] = "徐庶", ["char-xunyou"] = "荀攸", ["char-simahui"] = "司马徽",
            ["char-cuizhouping"] = "崔州平", ["char-zhangsong"] = "张松", ["char-lihui"] = "李恢",
            ["char-qiaozhou"] = "谯周", ["char-kuailiang"] = "蒯良", ["char-kuaiyue"] = "蒯越",
            ["char-diaochan"] = "貂蝉", ["char-daqiao"] = "大乔", ["char-xiaoqiao"] = "小乔",
            ["char-zhenji"] = "甄姬", ["char-caiwenji"] = "蔡文姬", ["char-huangyueying"] = "黄月英",
            ["char-wangyuanji"] = "王元姬", ["char-zhangchunhua"] = "张春华",
            ["char-wutugu"] = "兀突骨", ["char-mulu"] = "木鹿大王", ["char-duosi"] = "朵思大王",
            ["char-dongtuna"] = "董荼那",
            ["char-wenyang"] = "文鸯", ["char-wenqin"] = "文钦", ["char-zhugedan"] = "诸葛诞",
            ["char-guanqiujian"] = "毌丘俭", ["char-wangling"] = "王凌", ["char-weiguan"] = "卫瓘",
            ["char-dengzhong"] = "邓忠",
            ["char-chengyi"] = "成宜", ["char-liangxing"] = "梁兴", ["char-houxuan"] = "侯选",
            ["char-yangqiu"] = "杨秋", ["char-mawan"] = "马玩",
            ["char-panfeng"] = "潘凤", ["char-wuanguo"] = "武安国", ["char-xingdaorong"] = "邢道荣",
            ["char-leitong"] = "雷铜", ["char-wulan"] = "吴兰",
            // 扩充批 4 — 汉末朝堂/讨董名臣。
            ["char-wangyun"] = "王允", ["char-luzhi"] = "卢植", ["char-huangfusong"] = "皇甫嵩",
            ["char-zhujun"] = "朱儁", ["char-caiyong"] = "蔡邕", ["char-dongcheng"] = "董承",
            // 扩充批 4 — 魏晋文武。
            ["char-caoang"] = "曹昂", ["char-yangxiu"] = "杨修", ["char-cuiyan"] = "崔琰",
            ["char-maojie"] = "毛玠", ["char-dongzhao"] = "董昭", ["char-wanglang"] = "王朗",
            ["char-chenlin"] = "陈琳", ["char-miheng"] = "祢衡", ["char-lvqian"] = "吕虔",
            ["char-hanhao"] = "韩浩", ["char-simafu"] = "司马孚", ["char-huanfan"] = "桓范",
            ["char-jianggan"] = "蒋干", ["char-qinlang"] = "秦朗", ["char-guanning"] = "管宁",
            // 扩充批 4 — 蜀汉后进。
            ["char-chendao"] = "陈到", ["char-dongyun"] = "董允", ["char-yangyi"] = "杨仪",
            ["char-xiangchong"] = "向宠", ["char-liaoli"] = "廖立", ["char-fengxi"] = "冯习",
            ["char-futong"] = "傅彤", ["char-wuban"] = "吴班", ["char-gaoxiang"] = "高翔",
            ["char-lvkai"] = "吕凯", ["char-wangfu"] = "王甫",
            // 扩充批 4 — 东吴中生代。
            ["char-lvfan"] = "吕范", ["char-yufan"] = "虞翻", ["char-zhoufang"] = "周鲂",
            ["char-heqi"] = "贺齐", ["char-luotong"] = "骆统", ["char-zhuyi"] = "朱异",
            ["char-sunhuan"] = "孙桓", ["char-sunyi"] = "孙翊", ["char-panjun"] = "潘濬",
            ["char-sunjun"] = "孙峻", ["char-sunchen"] = "孙綝",
            // 扩充批 4 — 群雄/汉末诸侯。
            ["char-chendeng"] = "陈登", ["char-chengui"] = "陈珪", ["char-hanfu"] = "韩馥",
            ["char-zhangmiao"] = "张邈", ["char-zhangyang"] = "张杨", ["char-baoxin"] = "鲍信",
            ["char-liudai"] = "刘岱", ["char-yuantan"] = "袁谭", ["char-yuanshang"] = "袁尚",
            ["char-zhangyan"] = "张燕", ["char-guanhai"] = "管亥", ["char-caiyang"] = "蔡阳",
            ["char-chezhou"] = "车胄",
            // 扩充批 4 — 巾帼。
            ["char-bianfuren"] = "卞夫人", ["char-ganfuren"] = "甘夫人", ["char-mifuren"] = "糜夫人",
            ["char-wuguotai"] = "吴国太",
            // 扩充批 5 — 势力（184 纪元）。
            ["faction-han"] = "汉庭", ["faction-huangjin"] = "黄巾",
            // 扩充批 5 — 汉末群雄/凉州/黄巾/李郭。
            ["char-liuyan"] = "刘焉", ["char-liuyu"] = "刘虞", ["char-taoqian"] = "陶谦",
            ["char-gongsundu"] = "公孙度", ["char-qiaorui"] = "桥瑁", ["char-kongzhou"] = "孔伷",
            ["char-zhangchao"] = "张超", ["char-bocai"] = "波才", ["char-zhangmancheng"] = "张曼成",
            ["char-biansang"] = "边章", ["char-lisu"] = "李肃", ["char-yangfeng"] = "杨奉",
            ["char-hanxian"] = "韩暹", ["char-zhangji"] = "张济", ["char-fanchou"] = "樊稠",
            ["char-guosi"] = "郭汜", ["char-huchier"] = "胡车儿",
            // 扩充批 5 — 魏（后期）。
            ["char-jiakui"] = "贾逵", ["char-tianchou"] = "田畴", ["char-liangxi"] = "梁习",
            ["char-gaorou"] = "高柔", ["char-xinpi"] = "辛毗", ["char-luyu"] = "卢毓",
            ["char-xiahouba"] = "夏侯霸", ["char-wangchang"] = "王昶", ["char-shiba"] = "石苞",
            ["char-zhugexu"] = "诸葛绪", ["char-hujun"] = "胡遵", ["char-caoyu"] = "曹宇",
            // 扩充批 5 — 蜀（后期）。
            ["char-liushan"] = "刘禅", ["char-mazhong"] = "马忠", ["char-huoyi"] = "霍弋",
            ["char-luoxian"] = "罗宪", ["char-zhaotong"] = "赵统", ["char-zhaoguang"] = "赵广",
            ["char-dongjue"] = "董厥", ["char-fanjian"] = "樊建", ["char-jiangshu"] = "蒋舒",
            ["char-liuchen"] = "刘谌",
            // 扩充批 5 — 吴（后期）。
            ["char-sunhao"] = "孙皓", ["char-sunxiu"] = "孙休", ["char-sunliang"] = "孙亮",
            ["char-zhuju"] = "朱据", ["char-lvju"] = "吕据", ["char-liuzan"] = "留赞",
            ["char-tengyin"] = "滕胤", ["char-tangzi"] = "唐咨",
            // 扩充批 5 — 汉臣/荆州/巾帼。
            ["char-yangbiao"] = "杨彪", ["char-liuqi"] = "刘琦", ["char-liucong"] = "刘琮",
            ["char-xiahoushi"] = "夏侯氏", ["char-fuhou"] = "伏寿",
            // 扩充批 6 — 魏晋近臣/宿将。
            ["char-niujin"] = "牛金", ["char-shihuan"] = "史涣", ["char-wangbi"] = "王必",
            ["char-zhaoyan"] = "赵俨", ["char-dumu"] = "杜袭", ["char-zhangji-wei"] = "张既",
            ["char-suze"] = "苏则", ["char-hanji"] = "韩暨", ["char-gaotanglong"] = "高堂隆",
            ["char-liufang"] = "刘放", ["char-sunzi"] = "孙资", ["char-zhongyu"] = "钟毓",
            ["char-xunyi"] = "荀顗", ["char-wangsu"] = "王肃", ["char-dingmi"] = "丁谧",
            ["char-biyang"] = "毕轨", ["char-lisheng"] = "李胜", ["char-wangguan"] = "王观",
            ["char-chenjiao"] = "陈矫", ["char-dianman"] = "典满", ["char-xuyi"] = "许仪",
            ["char-panghui"] = "庞会",
            // 扩充批 6 — 蜀汉文武。
            ["char-huangquan"] = "黄权", ["char-liuba"] = "刘巴", ["char-zongyu"] = "宗预",
            ["char-xujing"] = "许靖", ["char-mengguang"] = "孟光", ["char-yinmo"] = "尹默",
            ["char-laijiang"] = "来敏", ["char-yangxi"] = "杨戏", ["char-liuyong"] = "刘永",
            ["char-liuli"] = "刘理", ["char-chenshi"] = "陈式",
            // 扩充批 6 — 东吴宗室/文武。
            ["char-zhangwen"] = "张温", ["char-yanjun"] = "严畯", ["char-zhaozi"] = "赵咨",
            ["char-lukai"] = "陆凯", ["char-zhuzhi"] = "朱治", ["char-shiji"] = "施绩",
            ["char-sunben"] = "孙贲", ["char-sunjiao"] = "孙皎", ["char-sunyu"] = "孙瑜",
            ["char-sundeng"] = "孙登", ["char-sunhe"] = "孙和", ["char-xuegong"] = "薛综",
            ["char-zhouchu"] = "周处",
            // 扩充批 6 — 巾帼。
            ["char-bufuren"] = "步夫人", ["char-panshu"] = "潘夫人",
            // 扩充批 6 — 董卓/吕布残部。
            ["char-niufu"] = "牛辅", ["char-dongmin"] = "董旻", ["char-songxian"] = "宋宪",
            ["char-weixu"] = "魏续", ["char-houcheng"] = "侯成", ["char-caoxing"] = "曹性",
            ["char-haomeng"] = "郝萌", ["char-yanxing"] = "阎行",
            // 扩充批 6 — 袁绍集团。
            ["char-chunyuqiong"] = "淳于琼", ["char-guotu"] = "郭图", ["char-fengji"] = "逢纪",
            ["char-xinping"] = "辛评", ["char-gaogan"] = "高干", ["char-yuanxi"] = "袁熙",
            ["char-lvkuang"] = "吕旷", ["char-lvxiang"] = "吕翔",
            // 扩充批 6 — 刘表/刘璋部将。
            ["char-liupan"] = "刘磐", ["char-zhangyun"] = "张允", ["char-songzhong"] = "宋忠",
            ["char-wangwei"] = "王威", ["char-lengbao"] = "泠苞", ["char-dengxian"] = "邓贤",
            ["char-gaopei"] = "高沛", ["char-yanghuai"] = "杨怀", ["char-zhengdu"] = "郑度",
            ["char-wanglei"] = "王累", ["char-liugui"] = "刘璝",
            // 扩充批 6 — 黄巾/异族/辽东。
            ["char-liupi"] = "刘辟", ["char-gongdu"] = "龚都", ["char-peiyuanshao"] = "裴元绍",
            ["char-budugen"] = "步度根", ["char-gongsunyuan"] = "公孙渊", ["char-maxiu"] = "马休",
            ["char-machie"] = "马铁",
            // 扩充批 6 — 汉末名士/方外。
            ["char-zhengxuan"] = "郑玄", ["char-zhangzhongjing"] = "张仲景", ["char-pangdegong"] = "庞德公",
            ["char-xushao"] = "许劭", ["char-huangwan"] = "黄琬", ["char-fuwan"] = "伏完",
            ["char-zhaoqi"] = "赵岐", ["char-liuyao"] = "刘繇", ["char-wangkuang"] = "王匡",
            ["char-huzhao"] = "胡昭", ["char-guanlu"] = "管辂",
            // 扩充批 7 — 魏晋。
            ["char-xiahouhui"] = "夏侯惠", ["char-xiahourong"] = "夏侯荣", ["char-xiahouwei"] = "夏侯威",
            ["char-caoxi"] = "曹羲", ["char-linghuyu"] = "令狐愚", ["char-changdiao"] = "常雕",
            ["char-simawang"] = "司马望", ["char-simazhou"] = "司马伷", ["char-simagan"] = "司马干",
            ["char-wangchen"] = "王沈", ["char-caofang"] = "曹芳", ["char-caomao"] = "曹髦",
            ["char-caohuan"] = "曹奂", ["char-wangjing"] = "王经", ["char-hufen"] = "胡奋",
            ["char-simayan"] = "司马炎", ["char-xunxu"] = "荀勖", ["char-caochun"] = "曹纯",
            ["char-hulie"] = "胡烈", ["char-qianhong"] = "牵弘",
            // 扩充批 7 — 蜀。
            ["char-zhugeshang"] = "诸葛尚", ["char-huangchengyan"] = "黄承彦", ["char-pengyang"] = "彭羕",
            ["char-xianglang"] = "向朗", ["char-donghe"] = "董和", ["char-huanghao"] = "黄皓",
            ["char-chenzhi"] = "陈祗", ["char-zhangshao"] = "张绍", ["char-yanghong"] = "杨洪",
            ["char-lvyi"] = "吕乂", ["char-duqiong"] = "杜琼", ["char-huji"] = "胡济",
            // 扩充批 7 — 吴。
            ["char-lvdai"] = "吕岱", ["char-quanji"] = "全纪", ["char-hulzong"] = "胡综",
            ["char-shiyi"] = "是仪", ["char-luyi"] = "陆胤", ["char-luji"] = "陆绩",
            ["char-sunkuang"] = "孙匡", ["char-sunshao"] = "孙韶", ["char-wufan"] = "吴范",
            ["char-liulve"] = "留略", ["char-buchan"] = "步阐", ["char-quanshang"] = "全尚",
            ["char-sunlang"] = "孙朗", ["char-weizhao"] = "韦昭", ["char-huagai"] = "华覈",
            // 扩充批 7 — 群雄/凉州。
            ["char-quyi"] = "麴义", ["char-caobao"] = "曹豹", ["char-hanmeng"] = "韩猛",
            ["char-jiangyiqu"] = "蒋义渠", ["char-hujzhen"] = "胡轸", ["char-yangding"] = "杨定",
            ["char-duanwei"] = "段煨", ["char-liyue"] = "李乐", ["char-hucai"] = "胡才",
            ["char-guanjing"] = "关靖", ["char-zoudan"] = "邹丹", ["char-jiaochu"] = "焦触",
            ["char-yuanyao"] = "袁遗", ["char-liuxun"] = "刘勋", ["char-leibo"] = "雷薄",
            ["char-chenlan"] = "陈兰", ["char-songjian"] = "宋建",
            // 扩充批 7 — 过五关六将/吕布八健将。
            ["char-kongxiu"] = "孔秀", ["char-hanfuluo"] = "韩福", ["char-mengtan"] = "孟坦",
            ["char-bianxi"] = "卞喜", ["char-wangzhi"] = "王植", ["char-qinqi"] = "秦琪",
            ["char-chenglian"] = "成廉",
            // 扩充批 7 — 巾帼。
            ["char-guozhao"] = "郭女王", ["char-xinxianying"] = "辛宪英", ["char-caojie"] = "曹节",
            ["char-wangyi"] = "王异",
            // 扩充批 7 — 羌蛮/南中。
            ["char-yueji"] = "越吉", ["char-cheliji"] = "彻里吉", ["char-ahuinan"] = "阿会喃",
            ["char-jinhuansanjie"] = "金环三结", ["char-mangyachang"] = "忙牙长", ["char-yongkai"] = "雍闿",
            ["char-gaoding"] = "高定", ["char-zhubao"] = "朱褒",
            // 扩充批 7 — 建安七子/荆南太守/谋士。
            ["char-wangcan"] = "王粲", ["char-ruanyu"] = "阮瑀", ["char-liuzhen"] = "刘桢",
            ["char-liudu"] = "刘度", ["char-zhaofan"] = "赵范", ["char-jinxuan"] = "金旋",
            ["char-fushiren"] = "士仁", ["char-xunchen"] = "荀谌", ["char-xuyou"] = "许攸",
            // 人才招揽原型（GDD_020 场景；console 同名 卧龙/骁将/能吏）。
            ["char-wolong"] = "卧龙", ["char-xiaojiang"] = "骁将", ["char-nengli"] = "能吏",
        };

        /// <summary>取某 id 的中文展示名；未登记则回退原文。</summary>
        public static string Of(string id)
            => Names.TryGetValue(id, out string? name) ? name : id;
    }
}
