using System.Collections.Generic;

namespace ThreeKingdom.Presentation.Screens
{
    /// <summary>
    /// 内部稳定 id → 玩家中文名的集中映射（占位期表现层用；后续可移入场景配置数据驱动）。
    /// 未登记的 id 回退原文，绝不崩 UI。<b>只影响展示，不影响权威 id</b>。
    /// </summary>
    public static class DisplayNames
    {
        private static readonly IReadOnlyDictionary<string, string> Names = new Dictionary<string, string>
        {
            ["subject-enemy-army"] = "敌军主力",
            ["advice-ambush"] = "设伏诱敌",
            ["faction-player"] = "本部",
            ["faction-lord"] = "君主",
            ["region-pass"] = "隘口",
            ["city-fanshui"] = "汜水关",
            ["city-hulao"] = "虎牢关",
            ["char-player-lord"] = "主公亲征",
            ["char-aide"] = "副将（军师）",

            // 群雄割据世界骨架（势力）。
            ["faction-yuan"] = "袁术",
            ["faction-sun"] = "孙吴",
            ["faction-cao"] = "曹操",
            ["faction-yuanshao"] = "袁绍",
            ["faction-liubei"] = "刘备",
            ["faction-lubu"] = "吕布",
            ["faction-liubiao"] = "刘表",
            ["faction-mateng"] = "马腾",
            ["faction-liuzhang"] = "刘璋",
            ["faction-zhanglu"] = "张鲁",
            ["faction-gongsun"] = "公孙瓒",
            // 城池。
            ["city-shouchun"] = "寿春",
            ["city-jianye"] = "建业",
            ["city-wujun"] = "吴郡",
            ["city-xuchang"] = "许昌",
            ["city-puyang"] = "濮阳",
            ["city-chenliu"] = "陈留",
            ["city-ye"] = "邺城",
            ["city-nanpi"] = "南皮",
            ["city-xiaopei"] = "小沛",
            ["city-xiapi"] = "下邳",
            ["city-xiangyang"] = "襄阳",
            ["city-xiliang"] = "西凉",
            ["city-chengdu"] = "成都",
            ["city-hanzhong"] = "汉中",
            ["city-beiping"] = "北平",
            // 君主。
            ["char-caocao"] = "曹操",
            ["char-yuanshao"] = "袁绍",
            ["char-liubei"] = "刘备",
            ["char-lubu"] = "吕布",
            ["char-liubiao"] = "刘表",
            ["char-mateng"] = "马腾",
            ["char-liuzhang"] = "刘璋",
            ["char-zhanglu"] = "张鲁",
            ["char-gongsun"] = "公孙瓒",
            ["char-sunquan"] = "孙权",
            ["char-yuan"] = "袁术",

            // 群雄割据扩充（势力）。
            ["faction-lijue"] = "李傕",
            ["faction-zhangxiu"] = "张绣",
            ["faction-kongrong"] = "孔融",
            ["faction-hansui"] = "韩遂",
            ["faction-shixie"] = "士燮",
            // 城池。
            ["city-juancheng"] = "鄄城",
            ["city-pingyuan"] = "平原",
            ["city-jinyang"] = "晋阳",
            ["city-runan"] = "汝南",
            ["city-kuaiji"] = "会稽",
            ["city-lujiang"] = "庐江",
            ["city-xuzhou"] = "徐州",
            ["city-jiangling"] = "江陵",
            ["city-jiangxia"] = "江夏",
            ["city-changsha"] = "长沙",
            ["city-jiangzhou"] = "江州",
            ["city-zitong"] = "梓潼",
            ["city-wuwei"] = "武威",
            ["city-jicheng"] = "蓟城",
            ["city-changan"] = "长安",
            ["city-luoyang"] = "洛阳",
            ["city-wancheng"] = "宛城",
            ["city-beihai"] = "北海",
            ["city-hanyang"] = "汉阳",
            ["city-jiaozhou"] = "交州",
            // 君主。
            ["char-sunce"] = "孙策",
            ["char-lijue"] = "李傕",
            ["char-zhangxiu"] = "张绣",
            ["char-kongrong"] = "孔融",
            ["char-hansui"] = "韩遂",
            ["char-shixie"] = "士燮",
            // 部将（武将目录 #2）。
            ["char-guanyu"] = "关羽",
            ["char-zhangfei"] = "张飞",
            ["char-zhaoyun"] = "赵云",
            ["char-zhugeliang"] = "诸葛亮",
            ["char-machao"] = "马超",
            ["char-huangzhong"] = "黄忠",
            ["char-weiyan"] = "魏延",
            ["char-pangtong"] = "庞统",
            ["char-jiangwei"] = "姜维",
            ["char-xiahoudun"] = "夏侯惇",
            ["char-zhangliao"] = "张辽",
            ["char-xuchu"] = "许褚",
            ["char-dianwei"] = "典韦",
            ["char-guojia"] = "郭嘉",
            ["char-xunyu"] = "荀彧",
            ["char-simayi"] = "司马懿",
            ["char-caoren"] = "曹仁",
            ["char-jiaxu"] = "贾诩",
            ["char-zhouyu"] = "周瑜",
            ["char-lusu"] = "鲁肃",
            ["char-lvmeng"] = "吕蒙",
            ["char-luxun"] = "陆逊",
            ["char-taishici"] = "太史慈",
            ["char-ganning"] = "甘宁",
            ["char-huanggai"] = "黄盖",
            ["char-yanliang"] = "颜良",
            ["char-wenchou"] = "文丑",
            ["char-gaoshun"] = "高顺",
            ["char-chengong"] = "陈宫",
            ["char-huaxiong"] = "华雄",
            ["char-haozhao"] = "郝昭",
            // 扩充批 1（演义名将）。
            ["char-xiahouyuan"] = "夏侯渊", ["char-zhanghe"] = "张郃", ["char-xuhuang"] = "徐晃",
            ["char-yujin"] = "于禁", ["char-yuejin"] = "乐进", ["char-lidian"] = "李典",
            ["char-caohong"] = "曹洪", ["char-caozhang"] = "曹彰", ["char-caopi"] = "曹丕",
            ["char-caozhi"] = "曹植", ["char-dengai"] = "邓艾", ["char-zhonghui"] = "钟会",
            ["char-guohuai"] = "郭淮", ["char-caozhen"] = "曹真", ["char-pangde"] = "庞德",
            ["char-wenpin"] = "文聘", ["char-chengyu"] = "程昱", ["char-simashi"] = "司马师",
            ["char-simazhao"] = "司马昭", ["char-huaxin"] = "华歆", ["char-manchong"] = "满宠",
            ["char-guanping"] = "关平", ["char-zhoucang"] = "周仓", ["char-liaohua"] = "廖化",
            ["char-madai"] = "马岱", ["char-wangping"] = "王平", ["char-guanxing"] = "关兴",
            ["char-zhangbao"] = "张苞", ["char-yanyan"] = "严颜", ["char-fazheng"] = "法正",
            ["char-masu"] = "马谡", ["char-jiangwan"] = "蒋琬", ["char-feiyi"] = "费祎",
            ["char-liyan"] = "李严", ["char-liufeng"] = "刘封",
            ["char-chengpu"] = "程普", ["char-handang"] = "韩当", ["char-zhoutai"] = "周泰",
            ["char-jiangqin"] = "蒋钦", ["char-chenwu"] = "陈武", ["char-lingtong"] = "凌统",
            ["char-xusheng"] = "徐盛", ["char-dingfeng"] = "丁奉", ["char-panzhang"] = "潘璋",
            ["char-zhuran"] = "朱然", ["char-zhugejin"] = "诸葛瑾", ["char-zhangzhao"] = "张昭",
            ["char-zhugeke"] = "诸葛恪", ["char-sunshangxiang"] = "孙尚香",
            ["char-dongzhuo"] = "董卓", ["char-liru"] = "李儒", ["char-zhangjiao"] = "张角",
            ["char-jiling"] = "纪灵", ["char-tianfeng"] = "田丰", ["char-jushou"] = "沮授",
            ["char-shenpei"] = "审配", ["char-gaolan"] = "高览", ["char-caimao"] = "蔡瑁",
            ["char-huangzu"] = "黄祖", ["char-zangba"] = "臧霸",
            // 扩充批 2。
            ["char-sunqian"] = "孙乾", ["char-mizhu"] = "糜竺", ["char-mifang"] = "糜芳",
            ["char-jianyong"] = "简雍", ["char-yiji"] = "伊籍", ["char-maliang"] = "马良",
            ["char-dengzhi"] = "邓芝", ["char-zhangyi"] = "张翼", ["char-zhangni"] = "张嶷",
            ["char-wuyi"] = "吴懿", ["char-huojun"] = "霍峻", ["char-mengda"] = "孟达",
            ["char-guansuo"] = "关索", ["char-zhugezhan"] = "诸葛瞻", ["char-fuqian"] = "傅佥",
            ["char-caoxiu"] = "曹休", ["char-caoshuang"] = "曹爽", ["char-wangshuang"] = "王双",
            ["char-tianyu"] = "田豫", ["char-qianzhao"] = "牵招", ["char-chentai"] = "陈泰",
            ["char-wangji"] = "王基", ["char-jiachong"] = "贾充", ["char-wangjun"] = "王濬",
            ["char-yanghu"] = "羊祜", ["char-duyu"] = "杜预", ["char-jiangji"] = "蒋济",
            ["char-liuye"] = "刘晔", ["char-chenqun"] = "陈群", ["char-zhongyao"] = "钟繇",
            ["char-caorui"] = "曹叡",
            ["char-sunjian"] = "孙坚", ["char-dongxi"] = "董袭", ["char-machongwu"] = "马忠",
            ["char-zhuhuan"] = "朱桓", ["char-quancong"] = "全琮", ["char-buzhi"] = "步骘",
            ["char-guyong"] = "顾雍", ["char-zhanghong"] = "张纮", ["char-kanze"] = "阚泽",
            ["char-lukang"] = "陆抗",
            ["char-huatuo"] = "华佗", ["char-zuoci"] = "左慈", ["char-yuji"] = "于吉",
            ["char-zhangbao-turban"] = "张宝", ["char-zhangliang-turban"] = "张梁", ["char-hejin"] = "何进",
            ["char-menghuo"] = "孟获", ["char-zhurong"] = "祝融", ["char-shamoke"] = "沙摩柯",
            ["char-zhangren"] = "张任", ["char-hanxuan"] = "韩玄", ["char-gongsunkang"] = "公孙康",
            ["char-tadun"] = "蹋顿", ["char-kebineng"] = "轲比能", ["char-yanbaihu"] = "严白虎",
            // 扩充批 3。
            ["char-xushu"] = "徐庶", ["char-xunyou"] = "荀攸", ["char-simahui"] = "司马徽",
            ["char-cuizhouping"] = "崔州平", ["char-zhangsong"] = "张松", ["char-lihui"] = "李恢",
            ["char-qiaozhou"] = "谯周", ["char-kuailiang"] = "蒯良", ["char-kuaiyue"] = "蒯越",
            ["char-diaochan"] = "貂蝉", ["char-daqiao"] = "大乔", ["char-xiaoqiao"] = "小乔",
            ["char-zhenji"] = "甄姬", ["char-caiwenji"] = "蔡文姬", ["char-huangyueying"] = "黄月英",
            ["char-wangyuanji"] = "王元姬", ["char-zhangchunhua"] = "张春华",
            ["char-wutugu"] = "兀突骨", ["char-mulu"] = "木鹿大王", ["char-duosi"] = "朵思大王",
            ["char-dongtuna"] = "董荼那",
            ["char-wenyang"] = "文鸯", ["char-wenqin"] = "文钦", ["char-zhugedan"] = "诸葛诞",
            ["char-guanqiujian"] = "毌丘俭", ["char-wangling"] = "王凌", ["char-weiguan"] = "卫瓘",
            ["char-dengzhong"] = "邓忠",
            ["char-chengyi"] = "成宜", ["char-liangxing"] = "梁兴", ["char-houxuan"] = "侯选",
            ["char-yangqiu"] = "杨秋", ["char-mawan"] = "马玩",
            ["char-panfeng"] = "潘凤", ["char-wuanguo"] = "武安国", ["char-xingdaorong"] = "邢道荣",
            ["char-leitong"] = "雷铜", ["char-wulan"] = "吴兰",
        };

        /// <summary>取某 id 的中文展示名；未登记则回退原文。</summary>
        public static string Of(string id)
            => Names.TryGetValue(id, out string? name) ? name : id;
    }
}
